#!/usr/bin/perl -w
my $svn=`svn info`;
my @svnlines = split(/\n/, $svn);

my $now = gmtime(time);
print "/*\n";
print " * Autogenerated on $now\n";
print " * by svnupdate.pl\n */\n\n";

foreach(@svnlines){
	if($_ =~ m/Revision/) {
		print "#define SVN_REVISION \"$_\"\n" ;
		s/Revision: //;
		print "#define SVN_REVISION_NUMBER $_\n" ;
	}
	print "#define SVN_LAST_CHANGED_REV \"$_\"\n" if m/Last Changed Rev/;
	print "#define SVN_LAST_CHANGED_DATE \"$_\"\n" if m/Last Changed Date/;
	print "#define SVN_LAST_CHANGED_AUTHOR \"$_\"\n" if m/Last Changed Author/;
	print "#define SVN_URL \"$_\"\n" if m/URL/;
}
